### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [eddie-atkinson/CITS3002-Labs#2]
Hey eddie-atkinson!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by eddie-atkinson** [comment]
Given that the unit coordinator for this unit (chris-mcdonald) has downvoted this issue, and that:

1. This repo is solely my work (except for the starter code provided by Chris)
2. This repo contains no proprietary code 
3. These lab exercises are totally ungraded and purely for the purposes of understanding the content

I will close this issue
